"""
Page: Reports - Generate/Export Insights
"""
import streamlit as st
import pandas as pd

st.set_page_config(page_title="Reports - NYEREKA Gender", page_icon="📄")

st.title("📄 Generate/Export Insights")

st.markdown("""
This page allows you to generate and export custom reports based on 
gender-related data for advocacy and policy purposes.
""")

# Load data
@st.cache_data
def load_data():
    try:
        studies = pd.read_csv("data/sample/studies.csv")
        resources = pd.read_csv("data/sample/study_resources.csv")
        quality = pd.read_csv("data/sample/quality_report.csv")
        return studies, resources, quality
    except FileNotFoundError:
        st.error("Data files not found.")
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

studies, resources, quality = load_data()

# Report generation options
st.sidebar.subheader("Report Options")

report_type = st.sidebar.selectbox(
    "Report Type",
    ["Summary Report", "Quality Assessment", "Resource Inventory", "Category Analysis"]
)

include_charts = st.sidebar.checkbox("Include Charts", value=True)

# Generate report
st.subheader(f"Generate {report_type}")

if report_type == "Summary Report":
    st.markdown("### Executive Summary Report")
    
    summary = f"""
# NYEREKA Gender Data Portal - Executive Summary

## Overview
This report summarizes available gender-related data resources in Rwanda.

## Key Statistics
- Total Studies: {len(studies)}
- Total Resources: {len(resources)}
- Categories Covered: {', '.join(studies['category'].unique()) if not studies.empty else 'N/A'}
- Geographic Coverage: {', '.join(studies['geographic_coverage'].unique()) if not studies.empty else 'N/A'}

## Data Quality
"""
    
    if not quality.empty:
        summary += f"""
- Average Quality Score: {quality['quality_score'].mean():.1f}
- High Quality Resources: {len(quality[quality['quality_badge'] == 'High'])}
- Medium Quality Resources: {len(quality[quality['quality_badge'] == 'Medium'])}
"""
    
    summary += """
## Key Recommendations

1. **For CSOs**: Use high-quality resources from official sources for advocacy
2. **For Researchers**: Consider data gaps when designing studies
3. **For Policy Makers**: Review quality caveats before making decisions

---
*Report generated by NYEREKA Gender Data Portal*
"""
    
    st.markdown(summary)
    
    st.download_button(
        label="Download Report",
        data=summary,
        file_name="executive_summary.txt",
        mime="text/plain"
    )

elif report_type == "Quality Assessment":
    st.markdown("### Data Quality Assessment Report")
    
    if not quality.empty:
        # Quality summary
        st.markdown("#### Quality Summary")
        
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Average Quality Score", f"{quality['quality_score'].mean():.1f}")
        with col2:
            st.metric("Highest Score", quality['quality_score'].max())
        
        # Quality by badge
        st.markdown("#### Quality Distribution")
        for badge in ["High", "Medium"]:
            count = len(quality[quality["quality_badge"] == badge])
            st.write(f"- **{badge}**: {count} resources")
        
        # Detailed assessment
        st.markdown("#### Resource Quality Details")
        
        merged = resources.merge(quality, on="resource_id") if not resources.empty else quality
        
        for idx, row in merged.iterrows():
            st.markdown(f"**{row.get('resource_title', row.get('resource_id'))}**")
            st.write(f"- Score: {row['quality_score']} - {row['quality_badge']}")
            st.write(f"- Caveats: {row['caveats']}")
            st.write("---")
    else:
        st.info("No quality data available")
    
    st.download_button(
        label="Download Quality Report",
        data="Quality report content...",
        file_name="quality_assessment.txt",
        mime="text/plain"
    )

elif report_type == "Resource Inventory":
    st.markdown("### Resource Inventory Report")
    
    if not resources.empty:
        st.dataframe(resources, use_container_width=True)
        
        # CSV export
        csv = resources.to_csv(index=False)
        st.download_button(
            label="Download Inventory (CSV)",
            data=csv,
            file_name="resource_inventory.csv",
            mime="text/csv"
        )
    else:
        st.info("No resources available")

elif report_type == "Category Analysis":
    st.markdown("### Category Analysis Report")
    
    if not studies.empty:
        for category in studies["category"].unique():
            st.markdown(f"#### {category}")
            cat_studies = studies[studies["category"] == category]
            
            for idx, row in cat_studies.iterrows():
                st.markdown(f"- **{row['study_title']}** ({row['year']}) - {row['institution']}")
            
            st.write("---")
        
        # Export
        csv = studies.to_csv(index=False)
        st.download_button(
            label="Download Category Analysis (CSV)",
            data=csv,
            file_name="category_analysis.csv",
            mime="text/csv"
        )
    else:
        st.info("No studies available")

# Tips section
st.markdown("---")
st.subheader("💡 Tips for Using Reports")

st.info("""
1. **For Advocacy**: Focus on high-quality resources and note caveats
2. **For Policy**: Review geographic coverage and temporal relevance
3. **For Research**: Check data disaggregation options
4. **For Validation**: Use the Data Quality page to verify sources
""")
